summonerid_url = ".api.riotgames.com/lol/summoner/v4/summoners/by-name/"
matchlist_url = ".api.riotgames.com/lol/match/v4/matchlists/by-account/"
matchrecord_url = ".api.riotgames.com/lol/match/v4/matches/"
api_key = "RGAPI-68ab9d96-5cf2-4225-b62b-5ac4f8f916ca"
region = "na1"
