summonerid_url = ".api.riotgames.com/lol/summoner/v4/summoners/by-name/"
matchlist_url = ".api.riotgames.com/lol/match/v4/matchlists/by-account/"
matchrecord_url = ".api.riotgames.com/lol/match/v4/matches/"
api_key = "RGAPI-42f74104-f923-4e8d-b555-be1fa0c2c8ad"
region = "na1"
