# Generated by Django 3.0 on 2019-12-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='empty', max_length=50),
            preserve_default=False,
        ),
    ]
